<?php

namespace GestionBoutiquesBundle\Repository;

/**
 * ProduitBoutiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitBoutiqueRepository extends \Doctrine\ORM\EntityRepository
{
    public function findCategoriesBoutique($unid)
    {
        $query = $this->getEntityManager()
            ->createQuery("Select DISTINCT cat.id from GestionBoutiquesBundle:ProduitBoutique prod JOIN prod.categorie cat
              WHERE prod.boutique=:unid ")
            //->setMaxResults(4)
            ->setParameter('unid', $unid);
        return $query->getResult();
    }

    public function findProduitsBoutiques($id_boutique, $valeur)
    {
        $query = $this->getEntityManager()
            ->createQuery("Select prod from GestionBoutiquesBundle:ProduitBoutique prod JOIN prod.boutique boutique
              WHERE boutique.id=:id_boutique AND prod.nomProduit LIKE :valeur  ")
            //->setMaxResults(4)
            ->setParameter('id_boutique', $id_boutique)
            ->setParameter('valeur', '%' . $valeur . '%');
        return $query->getResult();
    }

    public function findProduitsBoutique($id_boutique)
    {
        $query = $this->getEntityManager()
            ->createQuery("Select prod from GestionBoutiquesBundle:ProduitBoutique prod JOIN prod.boutique boutique
              WHERE boutique.id=:id_boutique")
            //->setMaxResults(4)
            ->setParameter('id_boutique', $id_boutique);
        return $query->getResult();
    }

    /*AND prod.nomProduit LIKE :valeur  */

    public function findCommandesBoutiquesVendus($boutique)
    {
        $query = $this->getEntityManager()
            ->createQuery("Select commande from GestionBoutiquesBundle:Commande commande JOIN commande.produit produit
              WHERE produit.boutique=:boutique ")
            ->setParameter('boutique',$boutique);
        //->setMaxResults(4)

        return $query->getResult();
    }
}
